name: e2e pipeline # The name of the entire workflow
run-name: Build, Deploy, Test - from user @${{ github.actor }} # Defines the name for an individual run instance of the workflow.

on:
 workflow_dispatch: # A manual trigger

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Temurin is an open-source build of the OpenJDK
          cache: maven # To cache the dependencies downloaded by Maven (the Java package manager) between workflow runs

      - name: Run Unit Tests
        run: mvn test
    
    
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false # True: If one job in a matrix fails, GitHub Actions will cancel all other jobs in that matrix.
      matrix:
       language: [ 'javascript', 'java' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Matrix Jobs: The matrix specifies language: ['javascript', 'java'], so there will be two jobs: one for JavaScript and one for Java.

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
 
     - name: Initialize CodeQL
       uses: github/codeql-action/init@v2
       with:
         languages: ${{ matrix.language }}
 
     - name: Autobuild
       uses: github/codeql-action/autobuild@v2
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v2
       with:
         category: "/language:${{matrix.language}}"
